### PR TITLE
Papers36

### PR DESCRIPTION
**Pull request by 251**
Add (mostly) Cloud9-based papers.

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251 .  I believe e.g. "Detecting MPI Usage Anomalies via Partial Program Symbolic Execution" does not use Cloud9, but that's minor.  Good to see more concurrency-related papers in the list!

**Comment by 251** [comment]
@ccadar It uses KLEE, I've added a "mostly" to the comment. Anything else?

**Comment by ccadar** [comment]
Thanks, @251 !

**Comment by ccadar** [comment]
And thanks for maintaining this list, it's a great resource for the community!  Almost 200?

**Comment by 251** [comment]
> Almost 200?

187 - I never really checked the early years ;)

**Pull request merged**
