### PR TITLE
Papers31

### PR DESCRIPTION
**Pull request by 251**

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251 .  I believe there is at least one other ASE 2020 that you might want to add here: http://zbchen.github.io/Papers_files/ase-2020-1.pdf

**Comment by 251** [comment]
The paper is not yet in ACM and I prefer to link to more stable urls.

**Comment by ccadar** [comment]
OK, I'll let you decide, although I personally prefer links which are not behind a paywall. But it is a trade-off, I know.
[Posted it in the wrong PR, sorry]

**Comment by ccadar** [comment]
> @ccadar You mean #234? It's just a reference - everyone should be able to find an article online...

@251 Well, then the title/authors/conference listing on this page would be enough, why add a link if you want people to find it separately? ;)  So I still think a direct link which is not behind a paywall is nicer, but as I said, I'll let you decide.

**Comment by 251** [comment]
@ccadar 
I prefer (permanent) links to the official source. They provide bibtex entries, make the paper accessible via corporate/university networks, enable scihub links with browser plugins (never tried of course), show citations, ... Links to papers are fine but authors change universities quite often and sites just vanish - I don't want to maintain it.

**Comment by ccadar** [comment]
You're overhyping a bit the official sources ;)  For me the paywall is the main issue though. 
Another option would be to just the link to a search for the paper title on Google Scholar.

**Comment by 251** [comment]
@ccadar
Take the link for the first paper: https://dl.acm.org/doi/10.1145/2451116.2451152 - in my browser there is already a "pdf" button on the right that links to google scholar and shows the pdf without using the paywall.

**Comment by ccadar** [comment]
Make sure you're not on the university network and not logged into the ACM DL via the university, and access it again: you'll see a "Get Access" button instead.

**Comment by ccadar** [comment]
It currently costs $15 for non-members.

**Comment by 251** [comment]
Hmm... I see "Get Access" above and "pdf" below. Maybe I'm indeed partially logged in via Imperial although the page on top says "sign in/Register".

**Comment by ccadar** [comment]
In any case: most publishers allow authors to post their papers on their websites, and anyone can find them if they're motivated enough.  The only question here is one of convenience: is it more convenient to link the the publisher version or the author version?

**Comment by 251** [comment]
The publisher version is more convenient for *me*. ;)

**Comment by ccadar** [comment]
Fair enough -- thanks for maintaining this!

**Pull request merged**
