### PR TITLE
klee-stats: csv conversion + crossref

### PR DESCRIPTION
**Pull request by 251**

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251 !  This LGTM.  However, I feel we should have all the info on `klee-stats` in a single place, and I think the `Tools` page would be the best place.  What do you think?

**Comment by 251** [comment]
I agree. I think the idea was to keep the Grafana section somewhere else as we haven't used/tested it that much.

**Comment by 251** [comment]
@ccadar I've moved the sections and also added a paragraph for `ktest-tool`.

**Comment by ccadar** [comment]
Looks great now, thanks, @251 !

**Pull request merged**
