### PR TITLE
Papers57

### PR DESCRIPTION
**Pull request by 251**

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251.  BTW, I noticed that the link to "Postconditioned Symbolic Execution" is broken.  Do you know if there an automated solution in GitHub Pages for checking links?

**Comment by 251** [comment]
@ccadar Fixed.

> automated solution in GitHub Pages for checking links

Might be possible but I think it's not the best idea to crawl 250+ addresses on every commit.

**Comment by ccadar** [comment]
I don't think we have as many commits to worry about this, but it's up to you. 
But since you moved most links to IEEE Explore and ACM DL, this will likely be less of an issue. 
Thanks for fixing those links manually.

**Comment by ccadar** [comment]
I see, thanks for the info.

**Pull request merged**
