### PR TITLE
Updated the list of KLEE open projects

### PR DESCRIPTION
**Pull request by ccadar**

### CODE REVIEW

**Comment by 251** [comment]
Just a comment: Arch already has a KLEE package: https://aur.archlinux.org/packages/klee/

You can check repos for different distributions quickly here: https://repology.org/project/klee/versions

**Comment by ccadar** [comment]
Thanks, @251 , that's great to know.

**Comment by ccadar** [comment]
@251 I also see one for openSUSE?

**Comment by 251** [comment]
@ccadar 
Only for Tumbleweed (the rolling-release version).

**Pull request merged**
