### PR TITLE
Removed --randomize-fork from Coreutils experiment flags

### PR DESCRIPTION
**Pull request by andreamattavelli**
As per https://github.com/klee/klee/issues/763

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @andreamattavelli .  I would actually mention the commit that removed it, https://github.com/klee/klee/commit/5133b98f1d989af94902366c6d02eb6447458aa1

**Comment by andreamattavelli** [comment]
@ccadar do you mean in the commit message?

**Comment by ccadar** [comment]
No, in the actual text.

**Comment by andreamattavelli** [comment]
@ccadar is it close to what you were thinking?

**Comment by ccadar** [comment]
Indeed.  But can you move it just after the paragraph saying " Some of these options have been renamed or removed..."  Thanks!

**Comment by andreamattavelli** [comment]
@ccadar Good point, I've forgotten about that paragraph.
Text moved and commits squashed.

**Comment by ccadar** [comment]
Thanks!

**Pull request merged**
