### PR TITLE
Papers26

### PR DESCRIPTION
**Pull request by 251**

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251 !  Why is it called Papers26?

**Comment by 251** [comment]
@ccadar branch name... it's the 26nd paper-adding PR.

**Comment by ccadar** [comment]
Wow, thanks for all these PRs, they form an excellent resource for KLEE.

**Comment by 251** [comment]
And we reached 150! :champagne:

**Comment by ccadar** [comment]
Indeed!

**Pull request merged**
