### PR TITLE
Fixed consistency between description and flag used in solver files

### PR DESCRIPTION
**Pull request by andreamattavelli**
A small (yet important) typo in the description of the solver files

### CODE REVIEW

**Comment by delcypher** [comment]
Thanks. A side thought though `--write-cvcs` is actually poorly named. It get's the constraints in the solver's native format. For STP this is CVC but for Z3 it actually gives back SMT-LIBv2.

**Comment by andreamattavelli** [comment]
> A side thought though --write-cvcs is actually poorly named.

Agree, same with `--write-pcs` in my opinion.

> It get's the constraints in the solver's native format. For STP this is CVC but for Z3 it actually gives back SMT-LIBv2.

Oh really? That doesn't make sense, though.

**Comment by delcypher** [comment]
> Oh really? That doesn't make sense, though.

It does make sense once you look at the implementation. I've created an issue for this https://github.com/klee/klee/issues/512.

Your change is fine to merge so thought I'll merge it now.

**Comment by andreamattavelli** [comment]
> It does make sense once you look at the implementation.

I was referring to the option name.

**Pull request merged**
