### PR TITLE
Updated STP documentation

### PR DESCRIPTION
**Pull request by andreamattavelli**
Updated website documentation to fix issue #28 and improve consistency between pages.

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @andreamattavelli .  This looks good, although I think it might be best to move the STP instructions to a separate page, and then reference it from both 2.9 and 3.4.   What do you think?

**Comment by andreamattavelli** [comment]
That's a good idea, since it can be reused for every LLVM version.
I will implement it.

**Comment by andreamattavelli** [comment]
@ccadar Updated the documentation by extracting the STP building description in a separate page.
Feedback is appreciated!

**Comment by ccadar** [comment]
Looks great, merging.  Thanks again!

**Pull request merged**
