### PR TITLE
Restructure web page

### PR DESCRIPTION
**Pull request by 251**
Here a proposal for the restructuring of the webpage, as discussed, with some minor changes on top.

~~It also removes the `klee-dev` page and in case we keep that change, we need to change [the issue template for klee](https://github.com/klee/klee/blob/4417ff31b45f540f0efcccd9f042d9a7ad429e6f/.github/ISSUE_TEMPLATE/question.md?plain=1#L13).~~

### CODE REVIEW

**Comment by ccadar** [comment]
Hi @251 thanks for your work on this, looks much better!
Just a few comments:
* I would keep the info on klee-dev on a separate page, as it's referenced from both the developer and the user support pages
* I would keep the tutorials in the `tutorials` directory.  We could consider putting it as a subdirectory of `docs`
* Minor: "Getting Started With KLEE" -> "Getting Started with KLEE"

**Comment by 251** [comment]
> I would keep the info on klee-dev on a separate page

It's a dangling page without any parent, that makes structure-wise not much sense.

> I would keep the tutorials in the tutorials directory.

And than have a directory without index page?!

**Comment by 251** [comment]
> I'm not sure what you mean without a parent, it will be linked from a couple of places.

It doesn't belong to any category. You click on it and no menu item on top is active/selected.

> And from GitHub, I think it's nicer to link to a dedicated page.

Why?

> I'm not sure having a directory without an index page is an issue -- we can just redirect to docs/#tutorials from there.

That would be an (ugly) but applicable option.

**Comment by 251** [comment]
@ccadar I've moved back the tutorials and added a redirection.

**Comment by ccadar** [comment]
Thanks, @251, much improved structure!

**Pull request merged**
