### PR TITLE
Fixed web page rendering

### PR DESCRIPTION
**Pull request by andreamattavelli**
Wrong indentation in the md file causes the page to not render correctly the code.

### CODE REVIEW

**Comment by andreamattavelli** [comment]
@ccadar I am going to merge it, if you don't have any complaint.

**Comment by ccadar** [comment]
Please do.

**Comment by ccadar** [comment]
BTW, you can also try the page on your own machine, see https://github.com/klee/klee.github.io/blob/master/README.md

**Comment by andreamattavelli** [comment]
Of course I did. I can't explain why but my Mac renders the page correctly,
while my Ubuntu desktop doesn't.
I will try both from now on. Sorry for the mess again.

**Comment by ccadar** [comment]
No worries, I also try it on a single machine usually.

**Pull request merged**
