### PR TITLE
Fix missing -I parameter

### PR DESCRIPTION
**Pull request by bananaappletw**

### CODE REVIEW

**Comment by andreamattavelli** [comment]
Hi @bananaappletw, from what I can see your patch modifies the tutorial to take into account the location of the example in the KLEE Git repository.
However you can try to invoke KLEE on the example without cloning and/or using the example repository, and thus your modifications would not be correct.

**Comment by bananaappletw** [comment]
@andreamattavelli 
I use docker image directly.
But how do include klee/klee.h without cloning.

**Comment by andreamattavelli** [comment]
@bananaappletw sorry I misunderstood what you wanted to do. Please next time add a description to the pull request :)
LGTM going to merge

**Comment by bananaappletw** [comment]
@andreamattavelli 
Sorry for that.
Thanks.

**Pull request merged**
