### PR TITLE
Updating installation instructions

### PR DESCRIPTION
**Pull request by ccadar**

### CODE REVIEW

**Comment by 251** [comment]
Doxygen is and should be an optional dependency imho. Did it change recently?

**Comment by ccadar** [comment]
Sure, but I think it's better to just install it.

**Comment by ccadar** [comment]
@251 Unless you feel strongly about this, let's merge this.

**Comment by 251** [comment]
Has anyone recently checked the output of doxygen? I mean, if we don't use it and normal users shouldn't use it, there is no point in installing it.

**Comment by ccadar** [comment]
Yes, it works :)  It was pointed to me a couple of times that we should add it as a dependency, most recently in #185 

Given the long list of packages that need to be installed and the long build instructions, if someone goes through the effort of installing KLEE, why not get doxygen documentation working right away?

**Comment by 251** [comment]
I just remember my Gentoo times when doxygen pulled in a plethora of dependencies and at the end the actual tool build failed because of a broken doxygen. :sob: LGTM

**Pull request merged**
