### PR TITLE
Restructure and improve KLEE's main page

### PR DESCRIPTION
**Pull request by ccadar**
Take a look!  I think it's more logical and complete than what we had before.

### CODE REVIEW

**Comment by 251** [comment]
It looks ok to me but the html is broken in many places (just check via e.g.: https://jsonformatter.org/html-validator). I would remove "to quickly try KLEE" and "&" ("& other ways to get started" -> "Other ways to get started") though.

**Comment by ccadar** [comment]
Thanks, @251 , but the validator doesn't show any issues that weren't there before, and I'm not sure how to fix the old issues right away.  So I propose to solve this in a different PR.  

I will remove "to quickly try KLEE".  I would personally leave the "&"s -- they are different types of links, and the "&" is supposed to indicate this.

**Comment by 251** [comment]
> I would personally leave the "&"s

Seems a little bit uncommon but ok. Just merge it and I see if I can fix the html.

**Comment by ccadar** [comment]
Thanks, @251.  Regarding the "&" I am happy to try other options, e.g., maybe italics works better.  
I was also wondering if there is a GitHub Action for checking the HTML validity.
In any case, I'll merge this now!

**Comment by ccadar** [comment]
Ha!  The way in looks now is different from what I see in the preview (same browser) and from what I intended...
More specifically, there should be a single column of boxed, with each box taking the full width... 
Maybe that broken HTML is to blame, but it seems unrelated to me...

**Comment by ccadar** [comment]
More info: the page looks fine under Firefox, but not under Chrome

**Comment by ccadar** [comment]
OK, ignore that -- went out and when I came back and refreshed the page, it looked fine in Chrome too ;)

**Pull request merged**
