### PR TITLE
Change tcmalloc as the default allocator

### PR DESCRIPTION
**Pull request by kren1**

### CODE REVIEW

**Comment by ccadar** [comment]
This looks good.  
@kren1 , somewhat unrelated to this, could you update the instructions you added for 3.8?  They now reference some PRs which are not relevant anymore.

**Comment by kren1** [comment]
I did that in this patch

**Comment by ccadar** [comment]
Thanks, @kren1 .  Ideally it would be a separate patch, but ok :)  Can you also change the reference to 669?  That PR was for 3.7 and it was merged.  Thanks!

**Comment by kren1** [comment]
Missed that one. Should be fixed now.

**Pull request merged**
