### PR TITLE
Moved Twitter news feed to the front of the page, for better visibility

### PR DESCRIPTION
**Pull request by ccadar**

### CODE REVIEW

**Comment by kren1** [comment]
I don't think this is better. I thought people use that page for the guides and documentation. Having twitter cluttering the utility of the page is annoying.

**Comment by ccadar** [comment]
I think the idea is to have more visibility into the news.  This way people can see the news (e.g., the announcements for the KLEE workshop) and then scroll down to documentation.

**Comment by ccadar** [comment]
Let me know if you have another suggestion for making the news feed visible. 
Overall, I think we should completely redo the main page, it's not great.

**Comment by ccadar** [comment]
Also, note that we already have the menu on top as shortcut to the different types of documentation.  In fact the installation guide is only accessible via the menu.

**Comment by 251** [comment]
But it doesn't really fit into the page structure and shifts the focus from documentation to news...

**Comment by ccadar** [comment]
Yes, I would like people to see the news.  Let's make this change until the workshop, and then we can revert it (or even better, redesign the page).  Are you happy with this?

**Comment by 251** [comment]
Can't we just add a temporary banner for the workshop?

**Comment by ccadar** [comment]
I'm fine with that to, if you offer to do this.

**Comment by 251** [comment]
Hurray... HTML and CSS ￼ :see_no_evil:

**Comment by 251** [comment]
See #115.

**Comment by ccadar** [comment]
Thanks, I'll close this PR then.

**Pull request closed without merging**
