### PR TITLE
remove llvm-gcc, update intrinsics example

### LINKED ISSUE #127: Remove `llvm-gcc` from documentation
`llvm-gcc` is part of LLVM 2.9. Recommend `wllvm` or clang instead.

### PR DESCRIPTION
**Pull request by 251**
Please carefully check the intrinsics document.

Should fix #127.

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @251 .  I'm not sure why you changed the code to `tmp = d == 3`, I thought the previous version was better for that discussion.

**Comment by ccadar** [comment]
(and make sure it doesn't change the bitcode generated by LLVM, I haven't checked)

**Comment by kren1** [comment]
Why did you add `#inclide klee/klee.h` . I know it is correct but makes the result less user friendly.

**Comment by 251** [comment]
Because otherwise we get "I pass silly arguments to klee_make_symbolic and KLEE crashes" mails.

**Comment by ccadar** [comment]
Can you have the first commit in a separate PR, so that we can merge it?

**Comment by 251** [comment]
@ccadar Done. Any ideas for an example that still works with clang?

**Comment by ccadar** [comment]
@251 I would go with this example, but I would change `(c==2) || (d==3)` to `(c==2) && (d==3)` so that we trigger an `invalid klee_assume` message, which is the more interesting part.  As a secondary point, I would use LLVM 6.0, so that we have a consistent LLVM version (the recommended one) across the documentation.  Thanks!

**Comment by 251** [comment]
@ccadar I've changed it to Clang 6 and `&&`.

**Comment by ccadar** [comment]
@251 looks great now, thanks!

**Pull request merged**
