### PR TITLE
Added documentation on Kleaver

### PR DESCRIPTION
**Pull request by andreamattavelli**
Added documentation on Kleaver with description of the new option 'assume-query-independence'.
Feedback is welcome!

### CODE REVIEW

**Comment by andreamattavelli** [comment]
@ccadar Updated documentation to match Kleaver's new option

**Comment by ccadar** [comment]
Hi @andreamattavelli , nice addition to the documentation!  The only comment is that this duplicates the info at http://klee.github.io/docs/options/#query-logging, so perhaps we should just have a link to that page and just add the Kleaver-specific parts in the section on logging?  What do you think?

**Comment by andreamattavelli** [comment]
Yeah, I was aware of this issue. However, I wanted to create a page for each tool that was self-contained.
In any case, it is not a big problem, I will fix it.

**Comment by andreamattavelli** [comment]
@ccadar I've updated the page with a link to KLEE options for query logging.

**Pull request merged**
