### PR TITLE
Update tutorials

### PR DESCRIPTION
**Pull request by kren1**
This updates the flags in the tutorials to prevent the `-O0` issues.

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @kren1 !  This looks great, the only comment is that I would use `-Xclang -disable-O0-optnone` to be consistent with our regression suite and the discussion in https://github.com/klee/klee/issues/902 that you reference.

Ah, and can you also update the broken link to `klee/klee.h`, perhaps with a link to GitHub?

**Comment by 251** [comment]
```
testing-coreutils.md

L109: Second[,] we
L110: This [is] similar
L110+ however[,] in LLVM 5.0 and later[,] compiling
L112: , therefore -> . Therefore,
L112+ , but explicitly - without comma?

testing-function.md

L47+ consistently use backticks for "-I", "klee.h" etc.
Also an example would be nice (klee_make_symbolic), but I know it's not your modification.
L54: hand[-]picked
L56: However[,] in [-the] later version[s]
L62: lat[-t]er
L62: not a sentence: Note if [...]. You can [...]
L64: -compile
L70: However[,]

testing-regex.md

L36: own optimisation[s]
```
Overall: a lot of places where we explain the optnone issue... Can't we separate it into a standalone article?

**Comment by kren1** [comment]
I addressed @251 feedback and moved Tutorial 1,2 to the `-O0` version. I kept coreutils on the `-O1` version because I think it's better for code that is going to be optimised. I added some discussion on that.

**Comment by ccadar** [comment]
Thanks!  In general, I would discourage a separate commit addressing the feedback, but I won't get too picky with documentation contributions :)

**Comment by kren1** [comment]
It's difficult to ammend each of the 3 commits individually. I can squash it all in 1.

**Comment by ccadar** [comment]
@kren1 Leave it like this now (the way to do it is to have separate commits for each tutorial, which you later squash into the appropriate initial commit).

**Pull request merged**
