### PR TITLE
Fixed the mention of needing Linux to run Docker.  Other small improv…

### PR DESCRIPTION
**Pull request by ccadar**
…ements to the text.

### CODE REVIEW

**Comment by 251** [comment]
Maybe replace "distribution" with "system"? Distribution followed by Ubuntu, OS, and Windows is a little bit strange.

**Comment by ccadar** [comment]
Thanks, @251 .  After re-reading the text, I think that sentence didn't say much, so I removed it.  What do you think?

**Comment by 251** [comment]
It's much better now, thanks.

**Comment by ccadar** [comment]
Thanks, I'll merge it then.

**Pull request merged**
