### PR TITLE
Added description of KLEE usage

### PR DESCRIPTION
**Pull request by andreamattavelli**
Added a description of the command-line usage of KLEE to improve the documentation and avoid errors (e.g issue [340](https://github.com/klee/klee/issues/340)).

### CODE REVIEW

**Comment by andreamattavelli** [comment]
@MartinNowack @ccadar Any comment is appreciated.

**Comment by ccadar** [comment]
Thanks, @andreamattavelli .  I would mention that if --posix-runtime is specified in the options to KLEE, one can use symbolic environment options as part of the program's options.   For consistency, please use KLEE, not Klee.

**Comment by andreamattavelli** [comment]
@ccadar I've added the citation to -posix-runtime and added a related section on the symbolic environment.
Comments are always appreciated to improve the section.

**Comment by andreamattavelli** [comment]
@andronat Updated the description with your suggestions.

**Comment by andronat** [comment]
@andreamattavelli yea I think is good! Thanks!

**Pull request merged**
