### PR TITLE
remove workshop banner

### PR DESCRIPTION
**Pull request by 251**
Finally, after 1 year...

### CODE REVIEW

**Comment by MartinNowack** [comment]
maybe we could have kept that somehow referenced for people to catch-up with workshop.

**Comment by 251** [comment]
What about adding the workshops to "KLEE-related Publications" further down?

**Comment by ccadar** [comment]
Yes, I was thinking about this.  Let's bring back a banner when the talks are available.

**Comment by ccadar** [comment]
@251 Do you mean adding the talks to that list?

**Comment by 251** [comment]
No, just a link to the webpage.

**Comment by MartinNowack** [comment]
Is there space maybe in the main menue?

**Comment by MartinNowack** [comment]
Moving projects under "Getting involved" and there is space ;)

**Comment by ccadar** [comment]
I think that could work well.

**Pull request merged**
