### PR TITLE
add Docovery and Shadow

### PR DESCRIPTION
**Pull request by tomek-kuchta**

### CODE REVIEW

**Comment by tomek-kuchta** [comment]
Please double-check the looks - I couldn't on my machine. Thanks!

**Comment by andreamattavelli** [comment]
@tomek-kuchta apparently you need to add extra spaces at the end of the line to correct indentation

**Comment by tomek-kuchta** [comment]
I've added the spaces

**Comment by andreamattavelli** [comment]
@tomek-kuchta unfortunately one space is not enough, you need to add two spaces at the end of each line

**Comment by tomek-kuchta** [comment]
@andreamattavelli I see. That's done.

**Comment by andreamattavelli** [comment]
@tomek-kuchta looks good! Please squash the commits and we're ready to merge!

**Comment by tomek-kuchta** [comment]
@andreamattavelli Hopefully it's ok now.

**Comment by andreamattavelli** [comment]
@tomek-kuchta Thanks and see you in a week

**Comment by tomek-kuchta** [comment]
@andreamattavelli Thank you!

**Pull request merged**
