### PR TITLE
Fix copyright and some alligments

### PR DESCRIPTION
**Pull request by kren1**

### CODE REVIEW

**Comment by 251** [comment]
That's a hack. We use a grid based system - can't you just use `g--half` class?

**Comment by kren1** [comment]
`g--half` doesn't work for me.

**Comment by 251** [comment]
```
diff --git a/_includes/footer.html b/_includes/footer.html
index 923e7f6..f2c6c70 100644
--- a/_includes/footer.html
+++ b/_includes/footer.html
@@ -19,14 +19,16 @@
         </li>
       </ul>
       <div class="main-footer__klee-section">
-        <p style="text-align: center">
+        <div class="g--half">
 {% if site.is_release %}
 Documentation for KLEE v{{site.current_version}}
 {% else %}
 Documentation for KLEE master branch
 {% endif %}
-        </p>
-        <p>&copy; Copyright 2009-2017, The KLEE Team.</p>
+        </div>
+        <div class="g--half g--last">
+          <p style="text-align: right; padding: 0 32px 0 0;">&copy; Copyright 2009-2017, The KLEE Team</p>
+        </div>
       </div>
     </div>
   </div>
diff --git a/css/main.scss b/css/main.scss
index a8ea377..0f77e18 100644
--- a/css/main.scss
+++ b/css/main.scss
@@ -304,10 +304,6 @@ main {
   padding-left: 17px;
 }
 
-.main-footer__klee-section p {
-  font-size: 13px;
-}
-
 .main-footer__title {
   color: $colorGrayDark;
   font-size: 26px;
```

**Comment by kren1** [comment]
You get the same misalignment as before, not applying.

**Comment by kren1** [comment]
Fixed

**Comment by 251** [comment]
Could you please re-add `.main-footer__klee-section p` - my mistake, I haven't checked the diff. What is the issue with `flex`?

**Comment by kren1** [comment]
If I don't delete that sections, it's not alligned ... Removing `flex makes the division in Documentation and Tutorials alligned. Just pull and have a look.

**Comment by 251** [comment]
Ah... that one. Agree.

**Comment by ccadar** [comment]
@251 can you merge this if you're happy with it?

**Pull request merged**
