### PR TITLE
Replaced links to buildbot with TravisCI

### PR DESCRIPTION
**Pull request by andreamattavelli**

### CODE REVIEW

**Comment by delcypher** [comment]
Unfortunately that URL shows the current running build (i.e. right now it's showing the build of one of my PRs) rather than what's in the master branch. That's not a huge problem though.

**Comment by andreamattavelli** [comment]
@delcypher Hmm, so you suggest to use https://travis-ci.org/klee/klee/builds instead. Well, I actually don't know which one to prefer :)

**Comment by delcypher** [comment]
@andreamattavelli I would suggest https://travis-ci.org/klee/klee/branches because you see the state of the master branch and the other branches.

I don't have any strong opinions though.

**Comment by andreamattavelli** [comment]
> @andreamattavelli I would suggest https://travis-ci.org/klee/klee/branches because you see the state of the master branch and the other branches.

Ok, seems more than reasonable.

**Comment by andreamattavelli** [comment]
Done.

**Comment by delcypher** [comment]
LGTM

**Pull request merged**
