### PR TITLE
Updated Minisat build instructions

### PR DESCRIPTION
**Pull request by adrianherrera**
The instructions say to use the STATICCOMPILE option, however if you look in the Minisat CMake file (https://github.com/stp/minisat/blob/master/CMakeLists.txt) the option is actually STATIC_BINARIES.

### CODE REVIEW

**Comment by andreamattavelli** [comment]
@adrianherrera Yes, the command is not correct as per issue #36. Before using STATIC_BINARIES, we should check whether the option is equivalent to STATICCOMPILE (which is a cryptominisat option).

**Comment by adrianherrera** [comment]
Ahh ok, cool. Sorry, I did not see that issue (I should have looked!).

**Comment by andreamattavelli** [comment]
@adrianherrera No worries. Quick question: have you tried compiling minisat with the STATIC_BINARIES option on?

**Comment by adrianherrera** [comment]
Yes I have. It works fine. However note that I didn't use cryptominisat (just minisat + STP).

**Comment by andreamattavelli** [comment]
@adrianherrera Thanks, seems to work fine.
@ccadar By using STATIC_BINARIES I was able to compile fine and avoid issue https://github.com/klee/klee/issues/431. Can you confirm?

**Comment by ccadar** [comment]
That's great!  It's not straightforward to confirm, as I'd need to rebuild the Docker image.  But if that's what you observe, let's update the instructions for building the Docker images.

**Comment by delcypher** [comment]
@ccadar @andreamattavelli Is there a good reason to build STP as a static library? I've built it as a shared library in the past and with the CMake build system everything worked fine.

**Comment by andreamattavelli** [comment]
@delcypher Well, it's what it is currently written in the documentation. I'll try to see if I can build it successfully with shared libraries.

**Comment by ccadar** [comment]
Indeed, there's no fundamental reason for which we should require a static build.  But unless there are objections, I would merge this PR, as it fixes the build instructions.

**Comment by adrianherrera** [comment]
ping :)

I noticed that this was still open. Is there anything else you would like me to do to get it merged?

**Comment by ccadar** [comment]
Thanks, @adrianherrera , I'll merge it now.   @delcypher , please open a different issue/PR if you'd like to discuss the shared library build.

**Pull request merged**
